### ISSUE TITLE
Part of clock widget is missing when paused during movie playback

### ISSUE THREAD

**Issue by Misenkooo** [Misenkooo/e2-openpli-plugin-MyMetrixHD#1]
If the movie is paused, pause canvas is too big and overlaps part of clock widget

**Comment by ghost** [comment]
Hallo.....:-)

have you ever made a automatic update....? 

look at Metrix Updater on this side....
http://www.et-view-support.com/Forum/showthread.php?11172-MetrixHD-**MyMetrix-PlugIn**

this is fixed.....

![Screenshot](https://f.cloud.github.com/assets/3519484/296712/36df7bf4-950f-11e2-99b8-c684c8eb759a.jpg)

**Comment by Misenkooo** [comment]
Hi, great, I didn't noticed it was fixed in updater. In v0.5 it was not fixed and I've used this one (there is no newer yet) as a base version so I will need to check your changes in your update repo and merge it into a trunk. You see, without version control is difficult to monitor changes when two or more people work on a project ;-)
