### ISSUE TITLE
ChannelSelection New 

### ISSUE THREAD

**Issue by ghost** [Misenkooo/e2-openpli-plugin-MyMetrixHD#2]
ChannelSelection New 

render="XPiconChannel"

Your size="220,96"

correct size ="220,132"

Thank you for your work ....

I now work with this. ipk version

**Comment by Heart1010** [comment]
Do we have to do something when used the unzipped version from you IPMAN and now use/install that .ipk version? (or just opkg install it on terminal)

**Comment by Misenkooo** [comment]
@IPMAN-online Ah, sorry, I will fix that. It was just for testing because I was using smaller picons before. Btw, next time feel free to change it right on github...

@Heart1010 no, just install it over. Existing files will be rewritten.

**Comment by Misenkooo** [comment]
It has been fixed, thanks for reporting this issue.
