### ISSUE TITLE
infowidget_ecm

### ISSUE THREAD

**Issue by ghost** [Misenkooo/e2-openpli-plugin-MyMetrixHD#3]
tell me

how did you get in the infowidget_ecm  the line under the display ....

![infowidget_ecm](https://f.cloud.github.com/assets/3519484/305534/82c4bf18-965c-11e2-91c4-2f1db8815ed5.jpg)

**Comment by Misenkooo** [comment]
Do you mean that "CAID: 0D96..." ???

**Comment by ghost** [comment]
No......

![82c4bf18-965c-11e2-91c4-2f1db8815ed5](https://f.cloud.github.com/assets/3519484/306895/94a0af90-96a1-11e2-910e-146a1d73752c.jpg)

**Comment by Misenkooo** [comment]
Ah, this one. It's ChannelInfoEncrypter converter + appropriate settings in infowidget ecm xml file...  Check it out... 
Color is taken from your settings...

**Comment by ghost** [comment]
and why is not with me.....?

![Screenshot](https://f.cloud.github.com/assets/3519484/307354/f13b8442-96be-11e2-9ecf-a7c573b4175d.jpg)

**Comment by Misenkooo** [comment]
What coding system does your provider use? Because from what I see it looks like none :-) The used system should be in bold. Check that xml file to see which systems are supported.

**Comment by Misenkooo** [comment]
According this site http://www.satpimps.com/showthread.php?113772-MTV-Networks-FTA, nickelodeon at position 19.2 in a MTV network packet is FTA and therefore no encryption system is used. That's the reason why you can't see it ;-) i have the same for few FTA channels I have...

**Comment by ghost** [comment]
The display is just as if the sender is encrypted and is then activated by a cam ...?

is that correct ?

**Comment by Misenkooo** [comment]
If there is an encryption used for a given channel and your recivier decrypting it, then a yellow line is displayed under appropriate encryption system. For me, it is CryptoWorks, therefore I have a yellowline. If a channel is encrypted also with other system, then appropriate encryption system is displayed in bold. Therefore you can see that Irdeto is only displayed in bold.

**Comment by ghost** [comment]
that's it ....

Thx

**Comment by Misenkooo** [comment]
:-)
